name: Run code in Docker
description: >
  Runs code in the context of a Rocky Linux 8 image.
inputs:
  options:
    description: Options to pass to docker
  run:
    description: The script to run in the container.
    required: true
runs:
  using: composite
  steps:
    - name: Run script within Docker
      uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
      with:
        image: ghcr.io/hpcflow/rockylinux8-python:latest
        options: ${{ inputs.options }}
        run: ${{ inputs.run }}
