name: Checkout this repository
description: >
  Runs code in the context of a Rocky Linux 8 image.
inputs:
  ref:
    description: Reference to check out.
    default: ${{ github.action_ref }}
  path:
    description: The path to check out as.
    default: github-support
runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: hpcflow/github-support
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}
        persist-credentials: false
