name: Set up Poetry
description: >
  Sets up Poetry, assuming Python is already set up.
inputs:
  version:
    description: The version of Poetry to install.
    required: true
outputs:
  python-path:
    description: The path to Python in the virtual environment.
    value: ${{ steps.code.outputs.python }}
  poetry-path:
    description: The path to the Poetry environment root. Use to locate activate script.
    value: ${{ steps.code.outputs.poetry }}

runs:
  using: composite
  steps:
    - shell: bash
      id: code
      run: |
        python -m pip install poetry==$VERSION
        poetry config virtualenvs.in-project true
        poetry config installer.modern-installation false
        if [ "$RUNNER_OS" = "Windows" ]; then
          poetry config installer.max-workers 1
        fi
        poetry run python $GITHUB_ACTION_PATH/paths.py >> $GITHUB_OUTPUT
      env:
        VERSION: ${{ inputs.version }}
